### ISSUE TITLE
Dummy Data: point shop 

### ISSUE THREAD

**Issue by lasyaneti** [HackIllinois/adonix#129]
1. for now, create new database called `shop`, create a collection within that called `items`
2. each item should store `name` (string), `quantity` (int), `price` (int), `isRaffle` (boolean) 
3. add an endpoint GET `/shop` that returns this entire collection and mobile can dynamically update the status of the point shop

**Comment by AydanPirani** [comment]
Add in an `itemId` field that's uniquely generated per item. Should create two tables, one for actual data and 1 for available quantities (because then we can modify that better). Add functionality to post/put/delete item, and put quantity.

**Comment by AydanPirani** [comment]
Resolved by #133
