### ISSUE TITLE
QR Scanning: Mentor Office Hours

### ISSUE THREAD

**Issue by lasyaneti** [HackIllinois/adonix#157]
### Purpose 
One of the ways attendees can earn points at the event will be by attending Mentor's office hours. Validating their attendance and automatic point addition will be done through the mobile apps and API. 

### Implementation 
1. Add `mentor_officehours` collection within `main` database 

2. Documents in this collection will store: `mentorId`: string, `mentorName`: string, `attendees`: string[]

3. `POST /mentor`  
- Needs elevated perms 
- Require `mentorName` in request body 
- Generate random `mentorId` similar to `eventId` 
- Add document to database  
- Return generated document in response

4. `GET /mentor`
- Require elevated perms 
- Nothing needed in request body 
- Return all information in `mentor_officehours`

5. `DELETE /mentor`
- Require elevated perms 
- Require `mentorId` in request body 
- Delete mentor from database
- Return success/error message (mentor doesn't exist, invalid perms, etc.) 

6. `POST /mentor/attendance`
- Require attendee role (in JWT) 
- Require `mentorId` in request body 
- Get `userId` from JWT 
- Note: attendees can only get points from one mentor at max ONCE. 
- Add userId to `attendees` list ONLY if not already included 
- If the mentorId is valid and the attendee has not already attended their office hours, update their points using the existing `updatePoints(userId, points)` function 
- ALSO update their coins by calling `updateCoins(userId, points)` 
- `point`/`coin` value for this is defaulted to 50 
- Return appropriate error if attendee tries to earn points for the same mentor more than once

**Comment by aletya** [comment]
modified files:
src/database/mentor-db.ts
src/database/models.ts
src/app.ts

new files:
src/services/mentor/mentor-formats.ts
src/services/mentor/mentor-router.test.ts
src/services/mentor/mentor-router.ts
