### ISSUE TITLE
Event Service 2.0

### ISSUE THREAD

**Issue by lasyaneti** [HackIllinois/adonix#19]
- [ ] GET /event/favorite/
- [ ] POST /event/favorite/
- [ ] DELETE /event/favorite/
- [ ] POST /event/staff/checkin/
- [ ] POST /event/checkin/

For Fall Team
- [ ] GET /event/code/{id}/
- [ ] PUT /event/code/{id}/
- [ ] GET /event/filter/?key=value

Do we need these? 
POST /event/track/
GET /event/track/event/EVENTID/
GET /event/track/user/USERID/

**Comment by AydanPirani** [comment]
![Image](https://github.com/HackIllinois/adonix/assets/49540156/78b0cd31-dfd0-45f2-b073-51f013ac2629)

Do these not already exist?
