### ISSUE TITLE
Checkin Service MVP

### ISSUE THREAD

**Issue by lasyaneti** [HackIllinois/adonix#20]
- [ ] GET /checkin/USERID/
- [ ] GET /checkin/
- [ ] POST /checkin/
- [ ] PUT /checkin/
- [ ] GET /checkin/list/

**Comment by AydanPirani** [comment]
https://docs.hackillinois.org/reference/services/Check-In/

> You will need a user token rather than a user id. User tokens are generated at the endpoints GET /user/qr/ and GET /user/qr/USERID/. If no token is provided, then the request will 422. If the token expires prior to when the request is received or the token is malformed, then a response with status 403 with the message "Bad user token.".

This seems kinda stupid - why are we returning request code `422` (request not processable) when we should be returning `400` (Bad Request)?

**Comment by AydanPirani** [comment]
Deleted service.
