### ISSUE TITLE
RSVP Service MVP

### ISSUE THREAD

**Issue by lasyaneti** [HackIllinois/adonix#21]
- [ ] GET /rsvp/USERID/
- [ ] GET /rsvp/
- [ ] POST /rsvp/
- [ ] PUT /rsvp/

**Comment by aletya** [comment]
NOTE: THIS SHOULD CORRELATE TO THE DECISION DB

GET /rsvp/:USERID/    :      check RSVP status for certain USERID, elevated perms only
GET /rsvp/                 :      get RSVP status of caller based on JWT token
POST /rsvp/               :      create a new rsvp of caller based on JWT token
PUT /rsvp/                 :      update RSVP of caller based on JWT token

FOR EXAMPLES, look at 
GET /user/:USERID (elevated perms)
vs.
GET /user (anyone)

and

GET /user/qr/:USERID (elevated perms)
vs.
GET /user/qr (anyone)
