### ISSUE TITLE
Figure out Testing Infrastructure

### ISSUE THREAD

**Issue by AydanPirani** [HackIllinois/adonix#3]
Find some sort of way to run tests, and ensure that things actually work! 

Maybe create an in-memory MongoDB (as per @anandani4136 's suggestion and go from there)? Maybe Jest?

**Comment by Timothy-Gonzalez** [comment]
https://github.com/nodkz/mongodb-memory-server Is what we should use, and it will allow us to run tests in parallel. We can also use `jest.config.js` to globally define the `beforeAll` and `afterAll` required so it's define in one central place.

Jest is fairly easy to set up

<details><summary>Example Code</summary>

```ts
// tests/your-module.test.ts
import mongoose from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';
import YourModel from '../src/your-module';

let mongoServer: MongoMemoryServer;

beforeAll(async () => {
  mongoServer = new MongoMemoryServer();
  const mongoUri = await mongoServer.getUri();
  mongoose.connect(mongoUri, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });
});

afterAll(async () => {
  await mongoose.disconnect();
  await mongoServer.stop();
});

describe('YourModel', () => {
  it('should save a document', async () => {
    const doc = new YourModel({ name: 'Test' });
    await doc.save();
    const foundDoc = await YourModel.findOne({ name: 'Test' });
    expect(foundDoc).toBeTruthy();
  });
});
```
</details>
