### ISSUE TITLE
Initialize Registration Service (MVP)

### ISSUE THREAD

**Issue by AydanPirani** [HackIllinois/adonix#53]
- [ ] GET /registration/
- [ ] GET /registration/USERID/
- [ ] GET /registration/attendee/USERID/
- [ ] GET /registration/attendee/
- [ ] POST /registration/attendee/
- [ ] PUT /registration/attendee/

**Comment by lasyaneti** [comment]
https://docs.hackillinois.org/reference/services/Registration/
