### ISSUE TITLE
Newsletter Service

### ISSUE THREAD

**Issue by lasyaneti** [HackIllinois/adonix#8]
This is a new service to store emails of those interested in hearing about HackIllinois and recruitment. Sign up through hackillinois.org and info.hackillinois.org only. Eventually connect this to sparkpost or a different mail service. 

- [x] endpoint reached
- [x] v1 endpoint error 
- [x] invalid input
- [x] typo in endpoint error -> 404 
- [x] existing newsletter, add user 
- [x] existing newsletter, existing user 
- [x] new newsletter

**Comment by AydanPirani** [comment]
linked to PR #7
